name: i538921-git-func
namespace: dts-integration-ger
runtime: nodejs18
source:
    gitRepository:
      baseDir: ./
      reference: master
      url: https://github.tools.sap/I538921/git-func.git
schemaVersion: v0
